### ISSUE TITLE
Feature request: deleting rows

### ISSUE THREAD

**Issue by amanda11** [StackStorm-Exchange/stackstorm-excel#15]
Excel pack doesn't allow you to delete rows.

I have a simple excel delete_rows action that will allow you to delete a row of a spreadsheet based on the key.

If this is something useful to community, then I could add some tests and supply for consideration.

**Comment by nmaludy** [comment]
I think this would be a great addition. I'm happy to review a PR if you want to put one together!

**Comment by amanda11** [comment]
I'll put a PR together. Just need to add unit-tests to the repo as there aren't any. So once I have unit-tests I'll submit a PR.

**Comment by martezr** [comment]
It looks like this issue can be closed as the pull request has been merged.

**Comment by arm4b** [comment]
thanks @martezr :+1:
